### ISSUE TITLE
Jabatan Administrator

### ISSUE THREAD

**Issue by adhellialaras** [digital-inovasi-bangsa/new-dupak#3]
Setelah membuat jabatan baru kemudian di Submit, kadang langsung kembali ke halaman awal Jabatan dengan notifikasi diatas, kadang tetap di halaman 'add' dengan notif di samping. namun data yang baru di buat tetap ditambahkan

**Comment by yogiyulianto** [comment]
del ini yang jabatan mau dipindah ke halaman awal atau yang add ya enaknya?

**Comment by adhellialaras** [comment]
kalo aku prefer ke halaman awal Jabatan mas
