### ISSUE TITLE
Master Jabatan vs Master Pegawai 

### ISSUE THREAD

**Issue by adhellialaras** [digital-inovasi-bangsa/new-dupak#4]
Di master jabatan, menginputkan jabatan disertai pilihan pangkat... namun ketika akan diinputkan ke master pegawai, jabatan tidak disertai dengan pangkat... jadi tidak tahu ketika memilih pangkatnya apa

![image](https://user-images.githubusercontent.com/54722050/78231878-a90d7200-74fd-11ea-89e2-197130ddc7e8.png)

![image](https://user-images.githubusercontent.com/54722050/78232320-436db580-74fe-11ea-8e27-aedd26b65a7f.png)

**Comment by yogiyulianto** [comment]
ini kurang yang pangkat yaa maksudnya?

**Comment by adhellialaras** [comment]
iya mas, jadi kalau di master pegawai di kasih keterangan jabatan, soalnya kalau gitu ada pangkat yang sama tapi di jabatan yang berbeda
