### ISSUE TITLE
Master Pegawai

### ISSUE THREAD

**Issue by adhellialaras** [digital-inovasi-bangsa/new-dupak#7]
No. HP dan NIP sudah ada notif error jika tidak memenuhi jumlah digit yang ditentukan, tapi jumlah digit yang di sediakan masing" hanya 12 digit.

Untuk No. HP bagusnya di buat fleksible saja karna tidak semua No. HP memiliki digit 13.

**Comment by yogiyulianto** [comment]
tak buat tidak ada batasan aja ya
