### ISSUE TITLE
Master Data

### ISSUE THREAD

**Issue by adhellialaras** [digital-inovasi-bangsa/new-dupak#9]
Penempatan Pangkat dan Jabatan Terbalik

![image](https://user-images.githubusercontent.com/54722050/78465417-a0948180-771f-11ea-8613-1632ba56f0a7.png)

![image](https://user-images.githubusercontent.com/54722050/78465423-bace5f80-771f-11ea-81aa-9bc21f58ca2d.png)

![image](https://user-images.githubusercontent.com/54722050/78465429-cb7ed580-771f-11ea-8654-140e35abf5ae.png)

Yang Pangkat diganti dengan Jabatan, dan sebaliknya.

**Comment by yogiyulianto** [comment]
ini semuanya kebalik po del?
